name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  testmnist:
    name: Train mnist
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: pip install numpy tqdm
    - name: Train MNIST
      run: PYTHONPATH="." python mnist.py
    - name: Install torch for testing
      run: pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Test Ops and DTypes
      run: |
       PYTHONPATH="." python test/test_ops.py
       PYTHONPATH="." python test/test_dtypes.py
