name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  testmnist:
    name: Train mnist
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: pip install numpy tqdm
    - name: Get code size
      run: PYTHONPATH="." python sz.py
    - name: Train MNIST
      run: PYTHONPATH="." python mnist.py

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install deps with mypy torch for testing
      run: pip install numpy tqdm mypy torch --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Test ops dtype optim
      run: |
        PYTHONPATH="." python test/test_ops.py
        PYTHONPATH="." python test/test_dtype.py
        PYTHONPATH="." python test/test_optim.py
    - name: Check types with mypy
      run: mypy